server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/imooc-demo?useUnicode=yes&characterEncode=utf-8
    username: root
    password: 123456
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  session:
    store-type: none
imooc:
  security:
    browser:
#      loginPage: /demo-signIn.html
#      loginType: REDIRECT
      loginType: JSON
    code:
      image:
        width: 100
        height: 50
        url: /order,/user/*
    social:
      qq:
        app-id: 10131627823
        app-secret: 34211e019a56566f7d44f4fe58380e69

logging:
  level:
    root: info